"""Codes de rejet/statut STABLES (PRD §11.4, ADR-ADV-004).

Chaînes stables et versionnées : elles sont exposées (CLI/API) et consommées par
`rejection_summary` ; elles ne doivent jamais changer silencieusement de valeur."""

from __future__ import annotations

# Maturité du modèle.
MODEL_NOT_SUPPORTED = "MODEL_NOT_SUPPORTED"
EXPERIMENTAL_REVIEW_ONLY = "EXPERIMENTAL_REVIEW_ONLY"

# Valeur / qualité / fraîcheur.
LOW_WORST_CASE_EV = "LOW_WORST_CASE_EV"
LOW_DATA_QUALITY = "LOW_DATA_QUALITY"
STALE_ODDS = "STALE_ODDS"              # fraîcheur MESURÉE et insuffisante
FRESHNESS_UNKNOWN = "FRESHNESS_UNKNOWN"  # fraîcheur NON mesurable (≠ STALE_ODDS)

# Filtres utilisateur.
USER_FILTERED_SPORT = "USER_FILTERED_SPORT"
USER_FILTERED_COMPETITION = "USER_FILTERED_COMPETITION"
USER_FILTERED_MARKET = "USER_FILTERED_MARKET"
USER_FILTERED_BOOKMAKER = "USER_FILTERED_BOOKMAKER"
USER_EXCLUDED_EVENT = "USER_EXCLUDED_EVENT"
USER_EXCLUDED_PARTICIPANT = "USER_EXCLUDED_PARTICIPANT"

# Validité / contraintes.
EVENT_ALREADY_STARTED = "EVENT_ALREADY_STARTED"
IDENTITY_CONFLICT = "IDENTITY_CONFLICT"
STAKE_LIMIT_TOO_LOW = "STAKE_LIMIT_TOO_LOW"
BOOSTED_MARKET_NOT_SUPPORTED = "BOOSTED_MARKET_NOT_SUPPORTED"

# Ranking (Lot 5) : un ELIGIBLE sans input REQUIRED est rejeté au ranking, jamais
# rendu au hasard (gardes défensives — la Policy garantit déjà ces inputs).
RANKING_MISSING_FRESHNESS = "RANKING_MISSING_FRESHNESS"
RANKING_MODEL_NOT_SUPPORTED = "RANKING_MODEL_NOT_SUPPORTED"

ALL_REASON_CODES = frozenset({
    MODEL_NOT_SUPPORTED, EXPERIMENTAL_REVIEW_ONLY,
    LOW_WORST_CASE_EV, LOW_DATA_QUALITY, STALE_ODDS, FRESHNESS_UNKNOWN,
    USER_FILTERED_SPORT, USER_FILTERED_COMPETITION, USER_FILTERED_MARKET,
    USER_FILTERED_BOOKMAKER, USER_EXCLUDED_EVENT, USER_EXCLUDED_PARTICIPANT,
    EVENT_ALREADY_STARTED, IDENTITY_CONFLICT, STAKE_LIMIT_TOO_LOW,
    BOOSTED_MARKET_NOT_SUPPORTED,
    RANKING_MISSING_FRESHNESS, RANKING_MODEL_NOT_SUPPORTED,
})
