"""Énumérations du domaine Advisor (PRD §8)."""

from __future__ import annotations

from enum import Enum


class RiskProfile(Enum):
    CONSERVATIVE = "CONSERVATIVE"
    BALANCED = "BALANCED"
    AGGRESSIVE = "AGGRESSIVE"
    CUSTOM = "CUSTOM"


class MaturityPolicy(Enum):
    SUPPORTED_ONLY = "SUPPORTED_ONLY"
    INCLUDE_EXPERIMENTAL_FOR_REVIEW = "INCLUDE_EXPERIMENTAL_FOR_REVIEW"


class CandidateStatus(Enum):
    ELIGIBLE = "ELIGIBLE"
    REVIEW_ONLY = "REVIEW_ONLY"
    REJECTED = "REJECTED"


class LineType(Enum):
    SINGLE = "SINGLE"
    COMBO = "COMBO"


class RecommendationOutcome(Enum):
    RECOMMENDED = "RECOMMENDED"
    REVIEW_CANDIDATES = "REVIEW_CANDIDATES"
    NO_OPPORTUNITY = "NO_OPPORTUNITY"
    NO_EVALUABLE_EVENTS = "NO_EVALUABLE_EVENTS"
    FAILED = "FAILED"


class DependencyStatus(Enum):
    """Dépendance d'une paire de legs (PRD §14.2). Ordre de priorité contractuel
    (Lot 9) : INCOMPATIBLE > STRUCTURALLY_DEPENDENT > STATISTICALLY_DEPENDENT >
    UNKNOWN > INDEPENDENT_ENOUGH. Seul INDEPENDENT_ENOUGH autorise le combo en V1."""

    INCOMPATIBLE = "INCOMPATIBLE"
    STRUCTURALLY_DEPENDENT = "STRUCTURALLY_DEPENDENT"
    STATISTICALLY_DEPENDENT = "STATISTICALLY_DEPENDENT"
    UNKNOWN = "UNKNOWN"
    INDEPENDENT_ENOUGH = "INDEPENDENT_ENOUGH"
